
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analysis;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int Float = 11;
  public static final int Integer = 10;
  public static final int SubOp = 7;
  public static final int Id = 12;
  public static final int IntType = 2;
  public static final int EOF = 0;
  public static final int OpenPar = 8;
  public static final int SumOp = 6;
  public static final int EndCmd = 4;
  public static final int error = 1;
  public static final int FloatType = 3;
  public static final int Att = 5;
  public static final int ClosePar = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IntType",
  "FloatType",
  "EndCmd",
  "Att",
  "SumOp",
  "SubOp",
  "OpenPar",
  "ClosePar",
  "Integer",
  "Float",
  "Id"
  };
}

